# Generated by Django 3.2 on 2021-04-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cemail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('cpassword', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField()),
                ('vehicle_no', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
