# Generated by Django 3.2 on 2021-04-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms_app', '0002_auto_20210416_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporterregistration',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
