# Generated by Django 3.2 on 2021-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms_app', '0004_userregistration_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporterregistration',
            name='role',
            field=models.CharField(default='transporter', max_length=100),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
