# Generated by Django 3.2 on 2021-04-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmms_app', '0006_auto_20210417_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bricks',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='cement',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='sand',
            name='qty',
        ),
    ]
