# Generated by Django 3.2 on 2021-04-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmms_app', '0007_auto_20210417_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bricks',
            name='available_amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bricks',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bricks',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cement',
            name='available_amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cement',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cement',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='godownstock',
            name='bricks',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bmms_app.bricks'),
        ),
        migrations.AlterField(
            model_name='godownstock',
            name='cement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bmms_app.cement'),
        ),
        migrations.AlterField(
            model_name='godownstock',
            name='sand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bmms_app.sand'),
        ),
        migrations.AlterField(
            model_name='sand',
            name='available_amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sand',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
