# Generated by Django 3.2 on 2021-04-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmms_app', '0009_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='godownstock',
            name='bricks',
        ),
        migrations.RemoveField(
            model_name='godownstock',
            name='cement',
        ),
        migrations.RemoveField(
            model_name='godownstock',
            name='sand',
        ),
        migrations.DeleteModel(
            name='Bricks',
        ),
        migrations.DeleteModel(
            name='Cement',
        ),
        migrations.DeleteModel(
            name='GoDownStock',
        ),
        migrations.DeleteModel(
            name='Sand',
        ),
    ]
