# Generated by Django 3.2 on 2021-04-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms_app', '0010_auto_20210419_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoDownStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
