# Generated by Django 3.2 on 2021-04-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmms_app', '0012_auto_20210419_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoDownStock',
        ),
    ]
