# Generated by Django 3.2 on 2021-04-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms_app', '0013_delete_godownstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoDownStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cement_amount', models.IntegerField()),
                ('cement_price', models.IntegerField()),
                ('sand_amount', models.IntegerField()),
                ('sand_price', models.IntegerField()),
                ('brick_amount', models.IntegerField()),
                ('brick_price', models.IntegerField()),
            ],
        ),
    ]
