# Generated by Django 3.2 on 2021-04-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms_app', '0014_godownstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godownstock',
            name='brick_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='godownstock',
            name='brick_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='godownstock',
            name='cement_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='godownstock',
            name='cement_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='godownstock',
            name='sand_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='godownstock',
            name='sand_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
