# Generated by Django 3.2 on 2021-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms_app', '0018_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='material_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
