# Generated by Django 3.2 on 2021-04-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmms_app', '0020_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
