# Generated by Django 3.2 on 2021-04-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmms_app', '0024_auto_20210428_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidorder',
            name='pay_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
